[package]
name = "rusty-redis-client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "examples/client.rs"

[dependencies]
rusty-redis-core = { path = "../core" }
anyhow = "1.0.68"
tokio = { version = "1.25.0", features = ["full"] }

[dev-dependencies]
tokio-test = "0.4.2"
